# Generated by Django 3.2.8 on 2023-12-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrativa',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='narrativa',
            name='nombre',
        ),
        migrations.AddField(
            model_name='narrativa',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='narrativa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
